let fruits=["Apple","Grapes","Mango"];
console.log(fruits);
console.log(fruits.length);
console.log(fruits[1]);
fruits.push("Banana");
console.log(fruits);
fruits.pop();
console.log(fruits);
fruits.unshift("Watermelon");
console.log(fruits);
fruits.shift();
console.log(fruits);